name: MSFE_Thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - ipykernel
  - pip
  - pip:
      - openpyxl
      - scikit-learn